### ISSUE TITLE
Update 00CREDITS and 00DISTS

### ISSUE THREAD

**Issue by masatake** [lsof-org/lsof#169]
- [x] #168. In addition, a check list used in reviewing the change for the man page must be written based on commit log of this pull request.
- [x] #156 lsof.8: Improve readability of complex adverbial clause in the manpage
- [x]  #170 Upstream FreeBSD patches from the sysutils/lsof port
